apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: devops-tools
  name: your-new-pv-rabbit
spec:
  capacity:
    storage: 10Gi # Thay thế bằng dung lượng tùy ý
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: your-storage-class-rabbit # Thay thế bằng StorageClass tương ứng hoặc đặt giá trị nếu PVC không có StorageClass
  hostPath:
    path: /data/data-01/rabbitmq # Thay thế bằng đường dẫn trên host của bạn





# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2023-10-03T06:12:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: rabbitmq
  name: data-rabbitmq-0
  namespace: devops-tools
  resourceVersion: "242875"
  uid: 476b4e7b-3413-455c-b31a-ffd59cbe1687
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: data
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
~                    