kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf-spark-master
  namespace: hadoop
  uid: 0aec7019-5316-462d-bd84-24afe3ea180f
  resourceVersion: '1318148'
  creationTimestamp: '2023-10-06T06:36:09Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"nginx.conf":"user nginx;\nworker_processes 
      1;\nevents {\n  worker_connections  10240;\n}\nhttp {\n  upstream
      spark-master {\n    server 192.168.1.11:7180;\n  }\n  server {\n   
      listen       80;\n    server_name  localhost;\n    location / {\n     
      #root   /usr/share/nginx/html; #Change this line\n      #index  index.html
      index.htm;\n      proxy_pass http://spark-master;\n      proxy_set_header
      Host $host;\n      proxy_set_header X-Real-IP $remote_addr;\n     
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n     
      proxy_set_header X-Forwarded-Proto $scheme;\n    }\n 
      }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-conf-spark-master","namespace":"hadoop"}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2023-10-06T12:01:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2023-10-09T08:05:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:nginx.conf: {}
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      upstream spark-master {
        server 192.168.1.11:8888;
      }
      server {
        listen       80;
        server_name  localhost;
        location / {
          #root   /usr/share/nginx/html; #Change this line
          #index  index.html index.htm;
          proxy_pass http://spark-master;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location ~ /api/kernels/ {
        proxy_pass            http://spark-master;
        proxy_set_header      Host $host;
        # websocket support
        proxy_http_version    1.1;
        proxy_set_header      Upgrade "websocket";
        proxy_set_header      Connection "Upgrade";
        proxy_read_timeout    86400;
       }  
       

      }
    }
