kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sonar-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
  labels:
    type: local
spec:
  storageClassName: sonar-storage
  claimRef:
    name: sonar-pvc
    namespace: sonar
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - huynt-11

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: sonar
spec:
  storageClassName: sonar-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

